version = 1

test_patterns = ["tests/", "test_*.py"]

[[analyzers]]
name = "python"
enabled = true

    [analyzers.meta]
    runtime_version = "3.8.10"  # Specify a specific version

    [analyzers.pylint]
    enabled = true

    [analyzers.flake8]
    enabled = true

    [analyzers.mypy]
    enabled = true

    [analyzers.bandit]
    enabled = true